version: "3"
services:
  service_a_container:
    container_name: service_a_container
    image: service_a
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - service_b_container

  service_b_container:
    container_name: service_b_container
    hostname: service_b
    image: service_b
    restart: always
    ports:
      - "8081:8081"
    environment:
      - spring.data.mongodb.host=mongodb_service
    depends_on:
      - mongodb_service

  mongodb_service:
    container_name: mongodb_service
    hostname: mongodb_service
    image: mongo
    restart: always
    ports:
      - "27017:27017"
