version: "3.5"
services:
  # SERVICE A
  service_a_container:
    container_name: service_a_container
    image: service_a
    restart: on-failure:5
    environment:
      - SERVICE_B_HOST=172.22.1.3
      - SERVICE_A_HOST=172.22.1.2
      - SERVICE_B_PORT=8081
      - SPRING_KAFKA_HOST=kafka
      - SPRING_KAFKA_PORT=9092
      # env of opentelemetry
      - OTEL_SERVICE_NAME=service_a_container
      - OTEL_METRICS_EXPORTER=none
      - OTEL_TRACES_EXPORTER=jaeger
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger_service:14250
    ports:
      - "8080:8080"
    depends_on:
      - service_b_container
      - kafka
      - jaeger_service
    networks:
      service_app_network:
        ipv4_address: 172.22.1.2

  # SERVICE B
  service_b_container:
    container_name: service_b_container
    image: service_b
    #    restart: always
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb_service
      - SPRING_KAFKA_HOST=kafka
      - SPRING_KAFKA_PORT=9092
      - SERVICE_A_HOST=172.22.1.2
      - SERVICE_B_HOST=172.22.1.3
      # env of opentelemetry
      - OTEL_SERVICE_NAME=service_b_container
      - OTEL_METRICS_EXPORTER=none
      - OTEL_TRACES_EXPORTER=jaeger
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger_service:14250
    depends_on:
      - mongodb_service
      - kafka
      - jaeger_service
    networks:
      service_app_network:
        ipv4_address: 172.22.1.3

  # JEAGER
  jaeger_service:
    container_name: jaeger_service
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14250:14250"
    networks:
      service_app_network:

  # MONGODB
  mongodb_service:
    container_name: mongodb_service
    hostname: mongodb_service
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      service_app_network:
        ipv4_address: 172.22.1.4

  # ZOOKEEPER
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      service_app_network:

  # KAFKA
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      service_app_network:

  # PROMETHEUS
  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    ports:
      - "9090:9090"
    environment:
      - SERVICE_A_HOST=172.22.1.2
      - SERVICE_B_HOST=172.22.1.3
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      service_app_network:

  # GRAFANA
  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    ports:
      - "4000:3000"
    restart: unless-stopped
    volumes:
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    networks:
      service_app_network:

#NETWORK
networks:
  service_app_network:
    name: service_app_network
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16
