# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
        - name: service-a-app
          image: ductram/service_a:latest
          ports:
            - containerPort: 8080
          env:
            - name: SERVICE_B_HOST
              value: service-bs
            - name: SERVICE_B_PORT
              value: "8081"
            - name: SPRING_KAFKA_HOST
              value: "kafka"
            - name: SPRING_KAFKA_PORT
              value: "9092"
            - name: REDIRECT_HOST
              value: service-as
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "1"
            limits:
              memory: "512Mi"
              cpu: "1"
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: service-as
spec:
  selector:
    app: service-a
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
