server:
  port: 8081

# logging:
#   level:
#     org.springframework.security: trace

app:
  service_a_host: http://127.0.0.1

spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_HOST:localhost}:${SPRING_KAFKA_PORT:29092}
  data:
    mongodb:
      database: service_b
      host: ${SPRING_DATA_MONGODB_HOST:localhost}
      port: 27017

  security:
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "service-a-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://127.0.0.1:8080/login/oauth2/code/service-a-client-oidc"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8080/"
              scopes:
                - "openid"
                - "employee.read"
            require-authorization-consent: true

      resourceserver:
        jwt:
          issuer-uri: http://abcdef:8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: "true"
