scrape_configs:
  - job_name: "prometheus-app-metrics"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:8081"]
        labels:
          application: "Service B Application"
