scrape_configs:
  # - job_name: "prometheus-app-metrics"
  #   metrics_path: "/actuator/prometheus"
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ["localhost:8081"]
  #       labels:
  #         application: "Service B Application"

  - job_name: "service-a"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 15s
    static_configs:
      - targets: ["service_a_container:8080"]

  - job_name: "service-b"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 15s
    static_configs:
      - targets: ["service_b_container:8081"]

  - job_name: "service-b-test-localhost"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 15s
    static_configs:
      - targets: ["localhost:8081"]
